name: didaction-xeus
channels:
  - https://prefix.dev/emscripten-forge-4x
  - https://prefix.dev/conda-forge
dependencies:
  - xeus-python
  - numpy=2.4.6
  - numba=0.67.0
  - llvmlite=0.49.0
  - matplotlib
